#!/usr/bin/env/python3
# -*- coding: utf-8 -*-

# Copyright © 2025-2026 Wenze Wei. All Rights Reserved.
#
# This file is part of PiscesL1.
# The PiscesL1 project belongs to the Dunimd Team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Content Watermark Operator

This module implements multi-modal content watermarking for AI-generated content.
It supports text, image, and audio watermarking with comprehensive embedding
and extraction capabilities.

Watermarking Modalities:

1. Text Watermarking:
   - Zero-width characters: U+200B (ZWJ), U+200C (ZWNJ), U+200D (LRM), U+FEFF (BOM)
   - 2-bit encoding per character: 00, 01, 10, 11
   - Redundancy encoding (1-5x) for robustness
   - Pseudo-random distribution based on seed
   - Invisible to humans, machine-readable

2. Image Watermarking:
   - DCT frequency domain embedding
   - Mid-band coefficient modification
   - Pairwise magnitude relationship encoding
   - Visible overlay option for explicit labeling
   - JPEG compression resistance

3. Audio Watermarking:
   - STFT frequency domain embedding
   - Ultrasonic frequency band (18-20kHz)
   - DSSS (Direct Sequence Spread Spectrum)
   - Frame synchronization for reliability
   - Robust against re-encoding

Key Features:
    - Automatic content type detection
    - Unified interface for all modalities
    - Configurable strength and redundancy
    - Seed-based reproducibility
    - Protocol integration for payload framing
    - Comprehensive metadata embedding

Usage Examples:
    >>> from opss.watermark.content_watermark_operator import PiscesLxContentWatermarkOperator
    >>> operator = PiscesLxContentWatermarkOperator()
    >>> 
    >>> # Embed watermark in text
    >>> watermarked_text = operator.embed_text(
    ...     "Hello, World!",
    ...     payload={"model": "PiscesL1", "user_id": "user123"}
    ... )
    >>> 
    >>> # Embed watermark in image
    >>> watermarked_image = operator.embed_image(
    ...     image_tensor,
    ...     payload={"model": "PiscesL1"}
    ... )
    >>> 
    >>> # Extract watermark from content
    >>> extracted = operator.extract(content)

Author: PiscesL1 Development Team
Version: 1.0.0
"""

import re
import json
import hashlib
import uuid
import time
import base64
import torch
import torch.fft
from typing import Dict, Any, Optional, Union, List
from datetime import datetime

from utils.opsc.base import PiscesLxBaseOperator
from utils.opsc.interface import PiscesLxOperatorResult, PiscesLxOperatorStatus
from configs.version import VERSION
from .config import (
    POPSSWatermarkConfig,
    POPSSWatermarkPayload,
    POPSSWatermarkJurisdiction,
    POPSSComplianceStandard,
    POPSSWatermarkRiskLevel
)
from .protocol_operator import POPSSWatermarkProtocolOperator

PiscesLxProtocolOperator = POPSSWatermarkProtocolOperator


class POPSSContentWatermarkOperator(PiscesLxBaseOperator):
    """
    Multi-modal content watermark operator.
    
    This operator provides comprehensive watermarking capabilities for text,
    image, and audio content generated by AI systems. It integrates with
    the protocol operator for payload framing and error detection.
    
    Attributes:
        config (POPSSWatermarkConfig): Watermark configuration
        protocol_operator (PiscesLxProtocolOperator): Payload framing operator
        zero_width_chars (List[str]): Zero-width character mapping
        
    Input Format:
        {
            "action": "embed" | "extract" | "verify",
            "content": str | torch.Tensor,    # Content to process
            "payload": Dict[str, Any],         # Watermark payload (for embed)
            "config": POPSSWatermarkConfig, # Configuration override
            "metadata": Dict[str, Any]        # Additional metadata
        }
        
    Output Format:
        {
            "action": str,
            "result": str | torch.Tensor | Dict,
            "watermark_id": str,
            "compliance": Dict
        }
    """
    
    def __init__(self, config: Optional[POPSSWatermarkConfig] = None):
        super().__init__()
        self.name = "pisceslx_content_watermark_operator"
        self.version = VERSION
        self.description = "Multi-modal content watermarking for text, image, and audio"
        self.config = config or POPSSWatermarkConfig()
        self.protocol_operator = PiscesLxProtocolOperator()
        self.zero_width_chars = ["\u200B", "\u200C", "\u200D", "\uFEFF"]
        self.char_to_bits = {v: k for k, v in {
            "00": self.zero_width_chars[0],
            "01": self.zero_width_chars[1],
            "10": self.zero_width_chars[2],
            "11": self.zero_width_chars[3]
        }.items()}
    
    @property
    def input_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "required": ["action", "content"],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["embed", "extract", "verify", "embed_text", "embed_image", "embed_audio"]
                },
                "content": {
                    "type": ["string", "tensor"],
                    "description": "Content to watermark or extract from"
                },
                "payload": {
                    "type": "object",
                    "description": "Watermark payload for embedding"
                },
                "metadata": {
                    "type": "object",
                    "description": "Additional metadata for payload"
                },
                "config": {
                    "type": "object",
                    "description": "Configuration override"
                },
                "strength": {
                    "type": "number",
                    "description": "Embedding strength override"
                },
                "redundancy": {
                    "type": "integer",
                    "description": "Redundancy level override"
                }
            }
        }
    
    @property
    def output_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {"type": "string"},
                "result": {"type": "any"},
                "watermark_id": {"type": "string"},
                "content_type": {"type": "string"},
                "payload": {"type": "object"},
                "compliance": {"type": "object"}
            }
        }
    
    def _execute_impl(self, inputs: Dict[str, Any], **kwargs) -> PiscesLxOperatorResult:
        action = inputs.get("action", "embed")
        content = inputs.get("content")
        
        if not content:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Content is required"
            )
        
        content_type = self._detect_content_type(content)
        
        if action == "embed":
            return self._embed(inputs, content_type)
        elif action == "extract":
            return self._extract(inputs, content_type)
        elif action == "verify":
            return self._verify(inputs, content_type)
        elif action == "embed_text":
            return self._embed_text(inputs)
        elif action == "embed_image":
            return self._embed_image(inputs)
        elif action == "embed_audio":
            return self._embed_audio(inputs)
        else:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=f"Unknown action: {action}"
            )
    
    def _embed(self, inputs: Dict[str, Any], content_type: str) -> PiscesLxOperatorResult:
        content = inputs.get("content")
        payload = inputs.get("payload", {})
        metadata = inputs.get("metadata", {})
        
        if content_type == "text":
            return self._embed_text({"content": content, "payload": payload, "metadata": metadata})
        elif content_type == "image":
            return self._embed_image({"content": content, "payload": payload, "metadata": metadata})
        elif content_type == "audio":
            return self._embed_audio({"content": content, "payload": payload, "metadata": metadata})
        else:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=f"Unsupported content type: {content_type}"
            )
    
    def _embed_text(self, inputs: Dict[str, Any]) -> PiscesLxOperatorResult:
        content = inputs.get("content")
        payload = inputs.get("payload", {})
        metadata = inputs.get("metadata", {})
        
        if not isinstance(content, str):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Text content must be a string"
            )
        
        if not content or not content.strip():
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.SUCCESS,
                output={"content": content, "watermarked": False},
                metadata={"reason": "Empty content"}
            )
        
        try:
            watermark_payload = self._create_payload(payload, metadata, "text")
            
            frame_result = self.protocol_operator._encode({
                "payload": watermark_payload.to_dict(),
                "redundancy": self.config.redundancy_level
            })
            
            if not frame_result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.FAILED,
                    error=f"Protocol encoding failed: {frame_result.error}"
                )
            
            bitstream = frame_result.output["bitstream"]
            
            watermarked = self._embed_bits_in_text(content, bitstream, watermark_payload.trace_chain)
            
            compliance = {
                "standard": self.config.standard.value,
                "jurisdiction": self.config.jurisdiction.code,
                "risk_level": self.config.risk_level.value,
                "type": "hidden_text_watermark",
                "detectable": True,
                "removable": False
            }
            
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.SUCCESS,
                output={
                    "content": watermarked,
                    "watermarked": True,
                    "watermark_id": watermark_payload.trace_chain,
                    "payload": watermark_payload.to_dict()
                },
                metadata={
                    "content_type": "text",
                    "compliance": compliance,
                    "bits_embedded": len(bitstream),
                    "redundancy": self.config.redundancy_level
                }
            )
            
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _embed_image(self, inputs: Dict[str, Any]) -> PiscesLxOperatorResult:
        image = inputs.get("content")
        payload = inputs.get("payload", {})
        metadata = inputs.get("metadata", {})
        
        if not isinstance(image, torch.Tensor):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Image content must be a torch.Tensor"
            )
        
        try:
            from .dct_operator import POPSSDCTOperator
            
            watermark_payload = self._create_payload(payload, metadata, "image")
            
            frame_result = self.protocol_operator._encode({
                "payload": watermark_payload.to_dict(),
                "redundancy": 1
            })
            
            if not frame_result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.FAILED,
                    error=f"Protocol encoding failed: {frame_result.error}"
                )
            
            bits = frame_result.output["bitstream"]
            
            dct_operator = POPSSDCTOperator()
            
            embed_result = dct_operator._embed({
                "image": image,
                "bits": bits,
                "strength": self.config.watermark_strength,
                "seed": hash(self.config.jurisdiction.code) & 0x7FFFFFFF,
                "band": "mid"
            })
            
            if not embed_result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.FAILED,
                    error=f"DCT embedding failed: {embed_result.error}"
                )
            
            watermarked = embed_result.output["image"]
            
            if self.config.mandatory_disclosure:
                visible_result = dct_operator._embed_visible({
                    "image": watermarked,
                    "visible_text": "AI-Generated"
                })
                if visible_result.is_success():
                    watermarked = visible_result.output["image"]
            
            compliance = {
                "standard": self.config.standard.value,
                "jurisdiction": self.config.jurisdiction.code,
                "risk_level": self.config.risk_level.value,
                "type": "image_watermark",
                "detectable": True,
                "removable": False
            }
            
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.SUCCESS,
                output={
                    "image": watermarked,
                    "watermarked": True,
                    "watermark_id": watermark_payload.trace_chain,
                    "payload": watermark_payload.to_dict()
                },
                metadata={
                    "content_type": "image",
                    "compliance": compliance,
                    "bits_embedded": embed_result.metadata.get("embedded_bits", 0)
                }
            )
            
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _embed_audio(self, inputs: Dict[str, Any]) -> PiscesLxOperatorResult:
        audio = inputs.get("content")
        payload = inputs.get("payload", {})
        metadata = inputs.get("metadata", {})
        
        if not isinstance(audio, torch.Tensor):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Audio content must be a torch.Tensor"
            )
        
        try:
            watermark_payload = self._create_payload(payload, metadata, "audio")
            
            frame_result = self.protocol_operator._encode({
                "payload": watermark_payload.to_dict(),
                "redundancy": 2
            })
            
            if not frame_result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.FAILED,
                    error=f"Protocol encoding failed: {frame_result.error}"
                )
            
            bits = frame_result.output["bitstream"]
            
            watermarked = self._embed_bits_in_audio(audio, bits, watermark_payload.trace_chain)
            
            compliance = {
                "standard": self.config.standard.value,
                "jurisdiction": self.config.jurisdiction.code,
                "risk_level": self.config.risk_level.value,
                "type": "audio_watermark",
                "detectable": True,
                "removable": False
            }
            
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.SUCCESS,
                output={
                    "audio": watermarked,
                    "watermarked": True,
                    "watermark_id": watermark_payload.trace_chain,
                    "payload": watermark_payload.to_dict()
                },
                metadata={
                    "content_type": "audio",
                    "compliance": compliance,
                    "bits_embedded": len(bits)
                }
            )
            
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _extract(self, inputs: Dict[str, Any], content_type: str) -> PiscesLxOperatorResult:
        content = inputs.get("content")
        
        if content_type == "text":
            return self._extract_from_text(content)
        elif content_type == "image":
            return self._extract_from_image(content)
        elif content_type == "audio":
            return self._extract_from_audio(content)
        else:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=f"Unsupported content type: {content_type}"
            )
    
    def _extract_from_text(self, text: str) -> PiscesLxOperatorResult:
        if not isinstance(text, str):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Text content must be a string"
            )
        
        try:
            rev_map = {v: k for k, v in {
                "00": self.zero_width_chars[0],
                "01": self.zero_width_chars[1],
                "10": self.zero_width_chars[2],
                "11": self.zero_width_chars[3]
            }.items()}
            
            symbols = []
            for ch in text:
                sym = rev_map.get(ch)
                if sym is not None:
                    symbols.append(sym)
            
            if not symbols:
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False, "reason": "No watermark symbols found"},
                    metadata={"content_type": "text"}
                )
            
            bitstream = ''.join(symbols)
            
            result = self.protocol_operator._decode({
                "bitstream": bitstream,
                "redundancy": self.config.redundancy_level
            })
            
            if result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={
                        "watermark_found": True,
                        "payload": result.output["payload"]
                    },
                    metadata={"content_type": "text"}
                )
            else:
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False, "reason": "Decode failed"},
                    metadata={"content_type": "text"}
                )
                
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _extract_from_image(self, image: torch.Tensor) -> PiscesLxOperatorResult:
        if not isinstance(image, torch.Tensor):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Image content must be a torch.Tensor"
            )
        
        try:
            from .dct_operator import POPSSDCTOperator
            
            dct_operator = POPSSDCTOperator()
            
            extract_result = dct_operator._extract({
                "image": image,
                "num_bits": 256,
                "seed": hash(self.config.jurisdiction.code) & 0x7FFFFFFF,
                "band": "mid"
            })
            
            if not extract_result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False},
                    metadata={"content_type": "image"}
                )
            
            bits = extract_result.output["bits"]
            
            result = self.protocol_operator._decode({
                "bitstream": bits,
                "redundancy": 1
            })
            
            if result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={
                        "watermark_found": True,
                        "payload": result.output["payload"]
                    },
                    metadata={"content_type": "image"}
                )
            else:
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False},
                    metadata={"content_type": "image"}
                )
                
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _extract_from_audio(self, audio: torch.Tensor) -> PiscesLxOperatorResult:
        if not isinstance(audio, torch.Tensor):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error="Audio content must be a torch.Tensor"
            )
        
        try:
            bits = self._extract_bits_from_audio(audio)
            
            if not bits:
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False},
                    metadata={"content_type": "audio"}
                )
            
            result = self.protocol_operator._decode({
                "bitstream": bits,
                "redundancy": 2
            })
            
            if result.is_success():
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={
                        "watermark_found": True,
                        "payload": result.output["payload"]
                    },
                    metadata={"content_type": "audio"}
                )
            else:
                return PiscesLxOperatorResult(
                    operator_name=self.name,
                    status=PiscesLxOperatorStatus.SUCCESS,
                    output={"watermark_found": False},
                    metadata={"content_type": "audio"}
                )
                
        except Exception as e:
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.FAILED,
                error=str(e)
            )
    
    def _verify(self, inputs: Dict[str, Any], content_type: str) -> PiscesLxOperatorResult:
        content = inputs.get("content")
        expected = inputs.get("expected", {})
        
        extract_result = self._extract(inputs, content_type)
        
        if not extract_result.output.get("watermark_found", False):
            return PiscesLxOperatorResult(
                operator_name=self.name,
                status=PiscesLxOperatorStatus.SUCCESS,
                output={"verified": False, "reason": "No watermark found"},
                metadata={"content_type": content_type}
            )
        
        payload = extract_result.output.get("payload", {})
        verified = True
        failed_checks = []
        
        if expected.get("model_id") and payload.get("model") != expected["model_id"]:
            verified = False
            failed_checks.append("model_id")
        
        if expected.get("standard") and payload.get("compliance", {}).get("standard") != expected["standard"]:
            verified = False
            failed_checks.append("standard")
        
        return PiscesLxOperatorResult(
            operator_name=self.name,
            status=PiscesLxOperatorStatus.SUCCESS,
            output={
                "verified": verified,
                "payload": payload,
                "failed_checks": failed_checks
            },
            metadata={"content_type": content_type}
        )
    
    def _detect_content_type(self, content: Any) -> str:
        if isinstance(content, str):
            return "text"
        elif isinstance(content, torch.Tensor):
            shape = content.shape
            if len(shape) == 3 and shape[0] in [1, 3, 4]:
                return "image"
            elif len(shape) == 1 or (len(shape) == 2 and shape[0] == 1):
                return "audio"
            elif len(shape) == 4:
                return "video"
        return "unknown"
    
    def _create_payload(self, payload: Dict[str, Any], metadata: Dict[str, Any], 
                       content_type: str) -> PiscesLxWatermarkPayload:
        watermark_payload = PiscesLxWatermarkPayload(
            model_id=self.config.model_id,
            version=self.config.version,
            user_hash=hashlib.sha256(
                metadata.get("user_id", "anonymous").encode()
            ).hexdigest()[:16],
            compliance={
                "standard": self.config.standard.value,
                "jurisdiction": self.config.jurisdiction.code,
                "risk_level": self.config.risk_level.value,
                "mandatory_disclosure": self.config.mandatory_disclosure,
                "tamper_evidence": self.config.tamper_evidence,
                "audit_required": self.config.audit_enabled,
                "content_type": content_type
            }
        )
        watermark_payload.trace_chain = str(uuid.uuid4())
        return watermark_payload
    
    def _embed_bits_in_text(self, content: str, bitstream: str, 
                          trace_chain: str) -> str:
        def bits_to_zwc(bitstream_inner: str) -> List[str]:
            if len(bitstream_inner) % 2 == 1:
                bitstream_inner += '0'
            symbols = [bitstream_inner[i:i+2] for i in range(0, len(bitstream_inner), 2)]
            return [self.zero_width_chars[int(s, 2)] for s in symbols]
        
        zwc_stream = bits_to_zwc(bitstream)
        
        key = f"{trace_chain}_{self.config.jurisdiction.code}"
        redundancy = self.config.redundancy_level
        
        watermarked = content
        
        for layer in range(redundancy):
            positions = []
            for i, _ch in enumerate(content):
                hash_input = f"{key}_{layer}_{i}"
                hash_val = hashlib.md5(hash_input.encode()).hexdigest()
                if hash_val[:2] == '00':
                    positions.append(i)
            
            temp = list(watermarked)
            idx = 0
            for pos in sorted(positions, reverse=True):
                if idx < len(zwc_stream):
                    temp.insert(pos, zwc_stream[idx])
                    idx += 1
            watermarked = ''.join(temp)
            
            if idx >= len(zwc_stream):
                break
        
        return watermarked
    
    def _embed_bits_in_audio(self, audio: torch.Tensor, bits: str, 
                            trace_chain: str) -> torch.Tensor:
        sample_rate = 44100
        min_freq = 18000
        max_freq = 20000
        amplitude = 0.01
        spread_factor = 10
        
        x = audio.flatten()
        n_fft = 1024
        hop = n_fft // 4
        win = torch.hann_window(n_fft, device=x.device, dtype=x.dtype)
        X = torch.stft(x, n_fft=n_fft, hop_length=hop, window=win, return_complex=True)
        
        freqs = torch.fft.rfftfreq(n_fft, d=1.0 / sample_rate).to(x.device)
        band_mask = (freqs >= min_freq) & (freqs <= max_freq)
        idx_band = torch.where(band_mask)[0]
        
        if idx_band.numel() == 0:
            return audio
        
        seed = int(hashlib.sha256(trace_chain.encode()).hexdigest(), 16) & 0x7FFFFFFF
        torch.manual_seed(seed)
        pn = torch.sign(torch.rand(spread_factor, device=x.device) - 0.5)
        
        bit_idx = 0
        for t in range(X.shape[1]):
            if bit_idx >= len(bits):
                break
            b = 1 if bits[bit_idx] == '1' else -1
            chips = pn[:min(spread_factor, idx_band.numel())] * b
            X[idx_band[:chips.numel()], t] = X[idx_band[:chips.numel()], t] * (1.0 + amplitude * chips)
            if t % 2 == 1:
                bit_idx += 1
        
        y = torch.istft(X, n_fft=n_fft, hop_length=hop, window=win, length=x.numel())
        return y.view(audio.shape)
    
    def _extract_bits_from_audio(self, audio: torch.Tensor) -> str:
        sample_rate = 44100
        min_freq = 18000
        max_freq = 20000
        spread_factor = 10
        
        x = audio.flatten()
        n_fft = 1024
        hop = n_fft // 4
        win = torch.hann_window(n_fft, device=x.device, dtype=x.dtype)
        X = torch.stft(x, n_fft=n_fft, hop_length=hop, window=win, return_complex=True)
        
        freqs = torch.fft.rfftfreq(n_fft, d=1.0 / sample_rate).to(x.device)
        band_mask = (freqs >= min_freq) & (freqs <= max_freq)
        idx_band = torch.where(band_mask)[0]
        
        if idx_band.numel() == 0:
            return ""
        
        pn = torch.sign(torch.rand(spread_factor, device=x.device) - 0.5)
        
        votes = []
        for t in range(0, X.shape[1] - 1, 2):
            mag = torch.abs(X[idx_band, t])
            chips = pn[:min(spread_factor, idx_band.numel())]
            corr = (mag[:chips.numel()] * chips).sum()
            votes.append('1' if corr > 0 else '0')
        
        bitstream = ''.join(votes)
        
        def majority_vote_decode(bits: str) -> str:
            if len(bits) < 3:
                return bits
            result = []
            for i in range(0, len(bits) - 2, 3):
                tri = bits[i:i+3]
                if tri.count('1') >= 2:
                    result.append('1')
                elif tri.count('0') >= 2:
                    result.append('0')
            return ''.join(result)
        
        return majority_vote_decode(bitstream)
    
    def embed_text(self, content: str, payload: Dict[str, Any], 
                  metadata: Optional[Dict[str, Any]] = None) -> str:
        """Convenience method to embed watermark in text."""
        result = self._embed_text({
            "content": content,
            "payload": payload,
            "metadata": metadata or {}
        })
        if result.is_success():
            return result.output["content"]
        raise ValueError(f"Text embedding failed: {result.error}")
    
    def embed_image(self, image: torch.Tensor, payload: Dict[str, Any],
                   metadata: Optional[Dict[str, Any]] = None) -> torch.Tensor:
        """Convenience method to embed watermark in image."""
        result = self._embed_image({
            "content": image,
            "payload": payload,
            "metadata": metadata or {}
        })
        if result.is_success():
            return result.output["image"]
        raise ValueError(f"Image embedding failed: {result.error}")
    
    def extract(self, content: Any) -> Dict[str, Any]:
        """Convenience method to extract watermark from content."""
        content_type = self._detect_content_type(content)
        if content_type == "text":
            result = self._extract_from_text(content)
        elif content_type == "image":
            result = self._extract_from_image(content)
        elif content_type == "audio":
            result = self._extract_from_audio(content)
        else:
            raise ValueError(f"Unsupported content type: {content_type}")
        
        if result.is_success():
            return result.output
        raise ValueError(f"Extraction failed: {result.error}")


def create_content_watermark_operator(
    config: Optional[POPSSWatermarkConfig] = None
) -> POPSSContentWatermarkOperator:
    """Factory function to create a content watermark operator."""
    return POPSSContentWatermarkOperator(config=config)


PiscesLxContentWatermarkOperator = POPSSContentWatermarkOperator


class POPSSWatermarkContentOperator(PiscesLxBaseOperator):
    """
    Enhanced Content Watermark Operator with unified factory.
    
    This class combines all content watermarking functions into a cohesive
    operator with factory methods.
    
    Methods:
        create: Factory method to create operator instance
    """
    
    def __init__(self, config: Optional[POPSSWatermarkConfig] = None):
        super().__init__()
        self.name = "pisceslx_content_watermark_operator"
        self.version = VERSION
        self.description = "Multi-modal content watermarking for text, image, and audio"
        self.config = config or POPSSWatermarkConfig()
        self.protocol_operator = PiscesLxProtocolOperator()
    
    @classmethod
    def create(cls, config: Optional[POPSSWatermarkConfig] = None) -> 'POPSSWatermarkContentOperator':
        """Factory method to create a content watermark operator."""
        return cls(config=config)


__all__ = [
    "POPSSContentWatermarkOperator",
    "POPSSWatermarkContentOperator",
    "create_content_watermark_operator"
]
