#!/usr/bin/env/python3

# Copyright © 2025 Wenze Wei. All Rights Reserved.
#
# This file is part of PiscesL1.
# The PiscesL1 project belongs to the Dunimd project team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from utils import PiscesLxCoreLog, PiscesLxCoreConfigManager

logger = PiscesLxCoreLog("PiscesLx.Tools.Help")

def help():
    print("PiscesL1 - Command Line Interface")
    print("")
    print("Usage:")
    print("  python manage.py [command] [options]")
    print("")
    print("Core Commands:")
    print("  setup       Environment setup and dependency installation")
    print("  update      Pull latest code from remote repository")
    print("  version     Show current version and changelog summary")
    print("  changelog   Show version history (supports --all / --version X.X.XXXX)")
    print("  help        Show this help message")
    print("")
    print("Training:")
    print("  train       Train the model")
    print("    --model_size <str>            e.g. 0.5B, 1.5B, 7B, 70B, 128B")
    print("    --dataset <str>               Training dataset name (e.g. Chinese2)")
    print("    --resume_ckpt <path>          Resume from checkpoint")
    print("    --reset_lr                    Reset LR after resume")
    print("    --quant | --no_quant          Force enable/disable quantization")
    print("    --force_quant                 Override config to enable quantization")
    print("    --force_lora                  Override config to enable LoRA")
    print("    --quant_bits {2,4,8}          Default: 4")
    print("    --rlhf                        Enable RLHF training")
    print("    --rlhf_dataset <str>          Default: dunimd/human_feedback")
    print("    --rlhf_lr <float>             Default: 1e-5")
    print("    --rlhf_batch_size <int>       Default: 4")
    print("    --rlhf_mini_batch_size <int>  Default: 1")
    print("    --rlhf_accum_steps <int>      Default: 4")
    print("    --rlhf_epochs <int>           Default: 3")
    print("    --rlhf_max_samples <int>      Default: 1000")
    print("    --rlhf_max_length <int>       Default: 512")
    print("")
    print("Inference:")
    print("  infer       Run inference (MCP integration/speculative decoding supported)")
    print("    --ckpt <path>                 Model checkpoint path")
    print("    --prompt <str>                Prompt text")
    print("    --image <path>                Image path (multimodal)")
    print("    --speculative                 Enable speculative decoding")
    print("    --draft_model <path>          Draft model path for speculative decoding")
    print("    --spec_gamma <int>            Speculative tokens per step (default: 4)")
    print("")
    print("Dataset:")
    print("  download    Download datasets for training")
    print("    --max_samples <int>           Max samples per dataset (default: 50000)")
    print("  dataset     Dataset management and conversion (see tools/dataset for details)")
    print("")
    print("Benchmark:")
    print("  benchmark   Model evaluation and benchmarking")
    print("    --list                         List all benchmarks")
    print("    --info <name>                  Show benchmark details")
    print("    --benchmark <name>             Run specific benchmark")
    print("    --config <path>                Model config path (default: configs/0.5B.json)")
    print("    --seq_len <int>                Sequence length (default: 512)")
    print("    --model <path>                 Model checkpoint path")
    print("    --perf                         Run performance benchmark")
    print("    --selftest                     Run built-in tests")
    print("")
    print("Monitor:")
    print("  check       Check GPU and dependencies")
    print("  monitor     System monitor (GPU/CPU/memory)")
    print("    --monitor_mode {standard}")
    print("    --update_interval <float>      Screen update interval (s)")
    print("    --log_interval <float>         Log aggregation interval (s)")
    print("")
    print("Cache:")
    print("  cache       Cache maintenance")
    print("    --cache_action {stats,clear-all,clear-dataset,clear-downloads}")
    print("")
    print("MCP:")
    print("  mcp         MCP tool management")
    print("    --mcp_action {status,warmup,refresh-cache}")
    print("    --mcp_host <str>               MCP server host (default: localhost)")
    print("    --mcp_port <int>               MCP server port (default: 8080)")
    print("")
    print("Watermark:")
    print("  watermark   Watermark detection for text or files")
    print("    --text <str>                   Text to check")
    print("    --file <path>                  File or directory to check")
    print("    --batch                        Enable directory batch mode")
    print("    --verbose, -v                  Verbose output")
    print("    --json                         Output JSON")
    print("")
    print("Examples:")
    print("  # Core")
    print("  python manage.py setup")
    print("  python manage.py update")
    print("  python manage.py version")
    print("  python manage.py changelog --all")
    print("  python manage.py changelog --version 1.0.0150")
    print("")
    print("  # Dataset")
    print("  python manage.py download --max_samples 50000")
    print("")
    print("  # Training")
    print("  python manage.py train --model_size 0.5B --dataset Chinese2")
    print("  python manage.py train --model_size 7B --dataset Chinese2 --quant --quant_bits 4 --force_lora")
    print("  python manage.py train --model_size 1.5B --dataset Chinese2 --resume_ckpt runs/last.pt --reset_lr")
    print("  python manage.py train --model_size 7B --dataset Chinese2 --rlhf --rlhf_dataset dunimd/human_feedback --rlhf_lr 1e-5")
    print("")
    print("  # Inference")
    print("  python manage.py infer --ckpt ckpt/model.pt --prompt 'Hello' --image path/to/image.jpg")
    print("  python manage.py infer --ckpt ckpt/model.pt --prompt 'Hi' --speculative --draft_model ckpt/draft.pt --spec_gamma 4")
    print("")
    print("  # Benchmark")
    print("  python manage.py benchmark --list")
    print("  python manage.py benchmark --info mmlu")
    print("  python manage.py benchmark --benchmark mmlu --config configs/0.5B.json --seq_len 4096 --model ckpt/model.pt")
    print("  python manage.py benchmark --perf --config configs/0.5B.json --selftest")
    print("")
    print("  # Monitor")
    print("  python manage.py monitor --monitor_mode standard --update_interval 1.0 --log_interval 5.0")
    print("")
    print("  # MCP agent tags in prompt")
    print("  python manage.py infer --prompt 'Search: <agent><an>web_search</an><ap1>latest AI news</ap1><ap2>5</ap2></agent>'")
    print("  python manage.py infer --prompt 'Calc: <agent><an>calculator</an><ap1>2 + 3 * 4</ap1></agent>'")
    print("")
    print("  # Watermark")
    print("  python manage.py watermark --text 'Check if this text contains a watermark'")
    print("  python manage.py watermark --file ./outputs/ --batch --verbose")
    print("  python manage.py watermark --text 'Test text' --json")

